-- ACESITA.CVTP_REGRAS_FAROL definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE ACESITA.CVTP_REGRAS_FAROL;

CREATE TABLE ACESITA.CVTP_REGRAS_FAROL (
                                           COD_REGRA_FAROL NUMBER(6,0),
                                           COD_AREA_NEGOCIO VARCHAR2(24),
                                           LIMIT_HORA_RETORNO NUMBER(4,0),
                                           PERC_LIMIT_AMARELO NUMBER(3,0),
                                           DTH_CAD_REG DATE,
                                           COD_REG_USUAR NUMBER(6,0),
                                           COD_REG_EMPRG NUMBER(3,0),
                                           CONSTRAINT PK_COD_REGRA_FAROL PRIMARY KEY (COD_REGRA_FAROL)
);
CREATE UNIQUE INDEX CVTP_REGRAS_FAROL_PK ON ACESITA.CVTP_REGRAS_FAROL (COD_REGRA_FAROL);


-- ACESITA.CVTP_SEGUIMENTO definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE ACESITA.CVTP_SEGUIMENTO;

CREATE TABLE ACESITA.CVTP_SEGUIMENTO (
                                         COD_SEG_CVTP NUMBER(6,0),
                                         DESC_SEGUIMENTO VARCHAR2(24),
                                         DTH_CAD_REG DATE,
                                         COD_REG_USUAR NUMBER(6,0),
                                         COD_REG_EMPRG NUMBER(3,0),
                                         CONSTRAINT CVTP_SEGUIMENTO_PK PRIMARY KEY (COD_SEG_CVTP),
                                         CONSTRAINT SYS_C00239482 CHECK ("COD_SEG_CVTP" IS NOT NULL)
);
CREATE UNIQUE INDEX CVTP_SEGUIMENTO_PK ON ACESITA.CVTP_SEGUIMENTO (COD_SEG_CVTP);


-- ACESITA.CVTP_PRODUTO definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE ACESITA.CVTP_PRODUTO;

CREATE TABLE ACESITA.CVTP_PRODUTO (
                                      NUN_SEQ_CVTP NUMBER(6,0),
                                      COD_SEG_CVTP NUMBER(6,0),
                                      COD_CLIENTE NUMBER(7,0),
                                      COD_LINHA_PRODT VARCHAR2(1),
                                      COD_REVIS_CVTP NUMBER(4,0),
                                      COD_AREA_APLIC VARCHAR2(1),
                                      COD_SITUA_CVTP VARCHAR2(2),
                                      DESC_COMPLEX_CVTP VARCHAR2(24),
                                      COD_REG_USUAR NUMBER(6,0),
                                      COD_REG_EMPRG NUMBER(3,0),
                                      COD_MERC_CVTP VARCHAR2(2),
                                      DESC_OUTRO_SEG VARCHAR2(24),
                                      DESC_MOTIV_CONSULTA VARCHAR2(24),
                                      COD_ENVIO_CUSTO VARCHAR2(1),
                                      COD_SETOR_AUTOMOT VARCHAR2(1),
                                      ACO_INTERN_CVTP VARCHAR2(24),
                                      COD_IDENT_FMACO VARCHAR2(5),
                                      COD_IDENT_ACOEX VARCHAR2(5),
                                      COD_ACAB_REVEST VARCHAR2(2),
                                      DESC_GRUPO_CVTP VARCHAR2(3),
                                      DESC_APLIC_CVTP VARCHAR2(24),
                                      DESC_QTD_FORNEC NUMBER(4,0),
                                      NORMA_REFER_CVTP VARCHAR2(1040),
                                      COD_NORM_CLIENTE VARCHAR2(1),
                                      DESC_NORMA_CLIENTE VARCHAR2(1040),
                                      DESC_COMP_QUIMICA VARCHAR2(1),
                                      COD_DIMENS_PROD VARCHAR2(1),
                                      DESC_TOLER_PROD VARCHAR2(1),
                                      DESC_PADRONIZ_ESP VARCHAR2(1),
                                      QTD_CONJ_DIMENS NUMBER(4,0),
                                      PES_LIQUI_PROD NUMBER(5,0),
                                      POS_BOB_TIRA VARCHAR2(1),
                                      DIAM_INTERN_BOB VARCHAR2(1),
                                      VLR_DIAM_ESPEC NUMBER(5,0),
                                      COD_ENSAIO_LABOR VARCHAR2(1),
                                      VLR_DUREZA_MIN NUMBER(6,3),
                                      VLR_DUREZA_MAX NUMBER(6,3),
                                      VLR_UNID_DUREZA VARCHAR2(1),
                                      LIMIT_ESCUM_MIN NUMBER(6,3),
                                      LIMIT_ESCUM_MAX NUMBER(6,3),
                                      LIMIT_ESCUM_UNID VARCHAR2(10),
                                      LIMIT_ESCDOIS_MIN NUMBER(6,3),
                                      LIMIT_ESCDOIS_MAX NUMBER(6,3),
                                      LIMIT_ESCDOIS_UNID VARCHAR2(10),
                                      LIMIT_RES_MIN NUMBER(6,3),
                                      LIMIT_RES_MAX NUMBER(6,3),
                                      LIMIT_RES_UNID VARCHAR2(10),
                                      VRL_ALONG_MIN NUMBER(6,3),
                                      VRL_ALONG_MAX NUMBER(6,3),
                                      VRL_ALONG_UNID VARCHAR2(10),
                                      TAM_GRAO_MIN NUMBER(6,3),
                                      TAM_GRAO_MAX NUMBER(6,3),
                                      TAM_GRAO_UNID VARCHAR2(10),
                                      VLR_OXALICO_MIN NUMBER(6,3),
                                      VLR_OXALICO_MAX NUMBER(6,3),
                                      VLR_OXALICO_UNID VARCHAR2(10),
                                      VLR_IMPACTO_MIN NUMBER(6,3),
                                      VLR_IMPACTO_MAX NUMBER(6,3),
                                      VLR_IMPACTO_UNID VARCHAR2(10),
                                      VLR_OUTROS VARCHAR2(124),
                                      VLR_OUTRO_MIN NUMBER(6,3),
                                      VLR_OUTRO_MAX NUMBER(6,3),
                                      VLR_OUTRO_UNID VARCHAR2(10),
                                      COD_TIPO_PERDA VARCHAR2(1),
                                      VLR_INDUC VARCHAR2(10),
                                      VRL_FREQUENCIA VARCHAR2(10),
                                      VALOR_WKG NUMBER(6,0),
                                      DESC_INFORMAC_FORN VARCHAR2(1024),
                                      DTH_CADAST_CVTP DATE,
                                      DESC_RECUSA_CVTP VARCHAR2(1024),
                                      DTH_RECUSA_CVTP DATE,
                                      DTH_RECEB_CVTP DATE,
                                      DTH_CADAST_RVTP DATE,
                                      DTH_ANALIS_RVTP DATE,
                                      COD_ARQUI_ANEXO CLOB,
                                      COD_CVTP_PAI NUMBER(6,0),
                                      IDC_CUSTO_PRVTP VARCHAR2(1),
                                      IDC_TIPO_FORNRVTP VARCHAR2(1),
                                      PRODUT_SAP_SIMRVTP VARCHAR2(124),
                                      IDC_FLUXO_ROTRVTP VARCHAR2(1),
                                      FLUXO_ROTIN_PRODRVTP VARCHAR2(256),
                                      COMPLEX_INDUST_RVTP VARCHAR2(1),
                                      IMPACT_RELEV_PROCERVTP VARCHAR2(1),
                                      DESC_IMPACT_RELEVRVTP VARCHAR2(512),
                                      DESC_CONDIC_FORNRVTP VARCHAR2(512),
                                      DESC_ANALIS_RISCORVTP VARCHAR2(512),
                                      COD_SITUA_RVTP VARCHAR2(1),
                                      IDC_ENVIO_RVTP VARCHAR2(1),
                                      DTH_ENVIO_RVTP DATE,
                                      IDC_FLAG_RVTP VARCHAR2(1),
                                      COD_ARQUI_ANEXORVTP CLOB,
                                      CONSTRAINT CVTP_PRODUTO_PK PRIMARY KEY (NUN_SEQ_CVTP),
                                      CONSTRAINT SYS_C00239484 CHECK ("NUN_SEQ_CVTP" IS NOT NULL),
                                      CONSTRAINT CVTP_PROD_SEG_FK FOREIGN KEY (COD_SEG_CVTP) REFERENCES ACESITA.CVTP_SEGUIMENTO(COD_SEG_CVTP)
);
CREATE UNIQUE INDEX CVTP_PRODUTO_PK ON ACESITA.CVTP_PRODUTO (NUN_SEQ_CVTP);


-- ACESITA.CVTP_PROPR_MECANICA definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE ACESITA.CVTP_PROPR_MECANICA;

CREATE TABLE ACESITA.CVTP_PROPR_MECANICA (
                                             NUN_PROPR_MECAN NUMBER(6,0),
                                             NUN_SEQ_CVTP NUMBER(6,0),
                                             COD_CONJ_PROP NUMBER(3,0),
                                             ESP_NOM_PRODT NUMBER(6,3),
                                             TOL_MIN_ESP NUMBER(6,3),
                                             TOL_MAX_ESP NUMBER(6,3),
                                             LAR_NOM_PRODT NUMBER(6,4),
                                             TOL_MIN_LAR NUMBER(6,4),
                                             TOL_MAX_LAR NUMBER(6,4),
                                             COMP_NOM_PRODT NUMBER(5,0),
                                             TOL_MIN_COMP NUMBER(5,0),
                                             TOL_MAX_COMP NUMBER(5,0),
                                             COD_TIPO_BORDA VARCHAR2(2),
                                             DTH_CAD_REG DATE,
                                             COD_REG_USUAR NUMBER(6,0),
                                             COD_REG_EMPRG NUMBER(3,0),
                                             CONSTRAINT CVTP_PROPR_MECAN_PK PRIMARY KEY (NUN_PROPR_MECAN),
                                             CONSTRAINT SYS_C00239487 CHECK ("NUN_PROPR_MECAN" IS NOT NULL),
                                             CONSTRAINT CVTP_PROPR_PROD_FK FOREIGN KEY (NUN_SEQ_CVTP) REFERENCES ACESITA.CVTP_PRODUTO(NUN_SEQ_CVTP)
);
CREATE UNIQUE INDEX CVTP_PROPR_MECAN_PK ON ACESITA.CVTP_PROPR_MECANICA (NUN_PROPR_MECAN);


-- ACESITA.CVTP_SOLIC_ANALISE definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE ACESITA.CVTP_SOLIC_ANALISE;

CREATE TABLE ACESITA.CVTP_SOLIC_ANALISE (
                                            COD_SOLIC_ANALISE NUMBER(6,0),
                                            NUN_SEQ_CVTP NUMBER(6,0),
                                            PROC_SOLIC_ANALIS VARCHAR2(124),
                                            DHT_SOLIC_ANALISE DATE,
                                            EMAIL_ENVIO_ANALISE VARCHAR2(1024),
                                            COD_AREA_SOLICIT VARCHAR2(5),
                                            EMAIL_DIREC_EMAIL VARCHAR2(1024),
                                            DESC_DETAL_EMAIL VARCHAR2(512),
                                            DTH_LIMITE_RETORN DATE,
                                            USUAR_SOLIC_ANALIS NUMBER(6,0),
                                            EMPRG_SOLIC_ANALIS NUMBER(3,0),
                                            DESC_ANALIS_EMAIL VARCHAR2(512),
                                            DHT_RETORN_ANALISE DATE,
                                            IDC_ANEXO_ANALISE VARCHAR2(1),
                                            USUAR_RETOR_ANALIS NUMBER(6,0),
                                            EMPRG_RETOR_ANALIS NUMBER(3,0),
                                            CONSTRAINT CVTP_SOLIC_ANALI_PK PRIMARY KEY (COD_SOLIC_ANALISE),
                                            CONSTRAINT SYS_C00239495 CHECK ("COD_SOLIC_ANALISE" IS NOT NULL),
                                            CONSTRAINT CVTP_SOLIC_ANALI_PROD_FK FOREIGN KEY (NUN_SEQ_CVTP) REFERENCES ACESITA.CVTP_PRODUTO(NUN_SEQ_CVTP)
);
CREATE UNIQUE INDEX CVTP_SOLIC_ANALI_PK ON ACESITA.CVTP_SOLIC_ANALISE (COD_SOLIC_ANALISE);


-- ACESITA.CVTP_SOLIC_CUSTO definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE ACESITA.CVTP_SOLIC_CUSTO;

CREATE TABLE ACESITA.CVTP_SOLIC_CUSTO (
                                          COD_SOLIC_CUSTO NUMBER(6,0),
                                          NUN_SEQ_CVTP NUMBER(6,0),
                                          COD_CLIENTE NUMBER(6,0),
                                          DESC_ACO_RVTP VARCHAR2(24),
                                          DESC_GRUPO_CVTP VARCHAR2(24),
                                          COD_ACAB_REVEST VARCHAR2(2),
                                          DETAL_DIMENS_ANALIS VARCHAR2(256),
                                          CUSTO_DIRETO_ABC NUMBER(9,0),
                                          DTH_CAD_REG DATE,
                                          COD_REG_USUAR NUMBER(6,0),
                                          COD_REG_EMPRG NUMBER(3,0),
                                          CONSTRAINT CVTP_SOLIC_CUSTO_PK PRIMARY KEY (COD_SOLIC_CUSTO),
                                          CONSTRAINT SYS_C00239498 CHECK ("COD_SOLIC_CUSTO" IS NOT NULL),
                                          CONSTRAINT CVTP_SOLIC_CUSTO_PROD_FK FOREIGN KEY (NUN_SEQ_CVTP) REFERENCES ACESITA.CVTP_PRODUTO(NUN_SEQ_CVTP)
);
CREATE UNIQUE INDEX CVTP_SOLIC_CUSTO_PK ON ACESITA.CVTP_SOLIC_CUSTO (COD_SOLIC_CUSTO);


-- ACESITA.CVTP_ANALIS_QUIMICA definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE ACESITA.CVTP_ANALIS_QUIMICA;

CREATE TABLE ACESITA.CVTP_ANALIS_QUIMICA (
                                             COD_ELEM_QUIMICO VARCHAR2(10),
                                             NUN_SEQ_CVTP NUMBER(6,0),
                                             COD_UNID_ELEM VARCHAR2(10),
                                             NUM_VLR_MIN NUMBER(6,3),
                                             NUM_VLR_MAX NUMBER(6,3),
                                             DTH_CAD_REG DATE,
                                             COD_REG_USUAR NUMBER(6,0),
                                             COD_REG_EMPRG NUMBER(3,0),
                                             CONSTRAINT CVTP_ANALIS_QUIM_PK PRIMARY KEY (COD_ELEM_QUIMICO),
                                             CONSTRAINT SYS_C00239490 CHECK ("COD_ELEM_QUIMICO" IS NOT NULL),
                                             CONSTRAINT CVTP_ANALIS_QUIM_PROD_FK FOREIGN KEY (NUN_SEQ_CVTP) REFERENCES ACESITA.CVTP_PRODUTO(NUN_SEQ_CVTP)
);
CREATE UNIQUE INDEX CVTP_ANALIS_QUIM_PK ON ACESITA.CVTP_ANALIS_QUIMICA (COD_ELEM_QUIMICO);


-- ACESITA.CVTP_CONTROLADORIA definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE ACESITA.CVTP_CONTROLADORIA;

CREATE TABLE ACESITA.CVTP_CONTROLADORIA (
                                            COD_ANALIS_CONTROL NUMBER(6,0),
                                            NUN_SEQ_CVTP NUMBER(6,0),
                                            COD_REVIS_CVTP NUMBER(6,0),
                                            COD_REG_USUAR NUMBER(6,0),
                                            COD_REG_EMPRG NUMBER(3,0),
                                            COD_SIGLA_LOTAC VARCHAR2(5),
                                            EMAIL_ANALIS_CUSTO VARCHAR2(48),
                                            PRODUT_SAP_SIMILAR VARCHAR2(48),
                                            ANO_MES_REFER DATE,
                                            QTDE_AÇO_ANALCUSTO NUMBER(5,0),
                                            STATUS_ANALIS_CUSTO VARCHAR2(4),
                                            DTH_INIC_ANALCUSTO DATE,
                                            DTH_ENVIO_ANALCUSTO DATE,
                                            CONSTRAINT CVTP_CONTROLAD_PK PRIMARY KEY (COD_ANALIS_CONTROL),
                                            CONSTRAINT SYS_C00239504 CHECK ("COD_ANALIS_CONTROL" IS NOT NULL),
                                            CONSTRAINT CVTP_CONTROLAD_PROD_FK FOREIGN KEY (NUN_SEQ_CVTP) REFERENCES ACESITA.CVTP_PRODUTO(NUN_SEQ_CVTP)
);
CREATE UNIQUE INDEX CVTP_CONTROLAD_PK ON ACESITA.CVTP_CONTROLADORIA (COD_ANALIS_CONTROL);


-- ACESITA.CVTP_GRUPO_EMAIL definition

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE ACESITA.CVTP_GRUPO_EMAIL;

CREATE TABLE ACESITA.CVTP_GRUPO_EMAIL (
                                          COD_GRUPO_AREA NUMBER(6,0),
                                          NUN_SEQ_CVTP NUMBER(6,0),
                                          SETOR_GRUPO_AREA VARCHAR2(20),
                                          DES_EMAIL_USUAR VARCHAR2(50),
                                          DTH_CAD_REG DATE,
                                          COD_REG_USUAR NUMBER(6,0),
                                          COD_REG_EMPRG NUMBER(3,0),
                                          CONSTRAINT COD_GRUPO_AREA_PK PRIMARY KEY (COD_GRUPO_AREA),
                                          CONSTRAINT FK_NUN_SEQ_CVTP FOREIGN KEY (NUN_SEQ_CVTP) REFERENCES ACESITA.CVTP_PRODUTO(NUN_SEQ_CVTP)
);
CREATE UNIQUE INDEX COD_GRUPO_AREA_PK ON ACESITA.CVTP_GRUPO_EMAIL (COD_GRUPO_AREA);